package Logic;

public enum Status {
    LOGIN_PAGE,
    MAIN_MENU_PAGE,
    COLLECTION_PAGE_FROM_PLAY,
    COLLECTIONS_PAGE,
    MAKE_DECK,
    CHANGE_DECK,
    SHOP_PAGE,
    BUY_PAGE,
    SELL_PAGE,
    WALLET_PAGE,
    BUY_PAGE_FROM_COLLECTION,
    FIRST_THREE_CARDS_PAGE,
    DISCOVER_THREE_WEAPONS,
    PLAY_PAGE,
    PLAY_PAGE_MY_TURN,
    PLAY_PAGE_MY_OPPONENT_TURN,
    CHOOSE_TARGET_FOR_SPELL,
    CHOOSE_TARGET_FOR_HERO_POWERS;
}
